### ISSUE TITLE
CoEvolution when? of adding champions

### ISSUE THREAD

**Issue by mdalvi** [tansey/sharpneat-tutorials#1]
I was taking a look at your Host-Parasite coevolution code, inside HostParasiteCoevolutionListEvaluator class. Can you tell me why would you add champion `_hallOfFame.Add(champ)` on every evaluation? whereas in regular TicTacToeCoevolutionEvaluator class you have opted to add champion every 50 evaluations.

**Comment by tansey** [comment]
Oh gosh... I have no idea. The repo is very old and I have not looked at it in about 5 years. No telling what I was thinking back then, but I don't really maintain this actively anymore. Sorry!
